(setf *house-db 
      '(
	;; first house
	((name red-house) 	
	 (type terrace)
	 (cost 175000)
	 (rooms ((kitchen ((dimensions (20 12))(appliances (cooker fridge dishwasher))))
		 (bathroom ((dimensions (10 14))(features (bath washbasin toilet))))
		 (bedrooms ((bedroom1 ((dimensions (15 21))(features (double-bed washbasin))))))))
	 (garden (pond lawn shed)))
	;; next house
	((name blue-house) 	
	 (type terrace)
	 (cost 210000)
	 (rooms ((kitchen ((dimensions (20 12))(appliances (cooker fridge dishwasher))))
		 (bathroom ((dimensions (10 14))(features (bath washbasin toilet))))
		 (bedrooms ((bedroom1 ((dimensions (8 20))(features (chandelier))))
			    (bedroom2 ((dimensions (8 20))(features (chandelier))))
			    (bedroom3 ((dimensions (8 20))(features (chandelier))))
			    (bedroom4 ((dimensions (15 21))(features (double-bed washbasin))))))))
	 (garden (pond lawn shed)))
	;; next house
	((name black-house) 	
	 (type terrace)
	 (cost 148000)
	 (rooms ((kitchen ((dimensions (20 12))(appliances (cooker fridge dishwasher))))
		 (bathroom ((dimensions (10 14))(features (bath washbasin toilet))))
		 (bedrooms ((bedroom1 ((dimensions (8 20))(features (chandelier))))
			    (bedroom2 ((dimensions (8 20))(features (chandelier))))
			    (bedroom3 ((dimensions (15 21))(features (double-bed washbasin))))))))
	 (garden (pond lawn shed)))
	
	((name yellow-house) 	
	 (type terrace)
	 (cost 167000)
	 (rooms ((kitchen ((dimensions (20 12))(appliances (cooker fridge dishwasher))))
		 (bathroom ((dimensions (10 14))(features (bath washbasin toilet))))
		 (bedrooms ((bedroom1 ((dimensions (8 20))(features (chandelier))))
			    (bedroom2 ((dimensions (8 20))(features (chandelier))))
			    (bedroom3 ((dimensions (8 20))(features (chandelier))))
			    (bedroom4 ((dimensions (8 20))(features (chandelier))))
			    (bedroom5 ((dimensions (8 20))(features (chandelier))))
			    (bedroom6 ((dimensions (15 21))(features (double-bed washbasin))))))))
	 (garden (pond lawn shed)))
	
	((name purple-house) 	
	 (type terrace)
	 (cost 267000)
	 (rooms ((kitchen ((dimensions (20 12))(appliances (cooker fridge dishwasher))))
		 (bathroom ((dimensions (10 14))(features (bath washbasin toilet))))
		 (bedrooms ((bedroom1 ((dimensions (8 20))(features (chandelier))))
			    (bedroom2 ((dimensions (8 20))(features (chandelier))))
			    (bedroom3 ((dimensions (15 21))(features (double-bed washbasin))))))))
	 (garden (pond lawn shed)))
	((name green-house)
	 (type glass))))